/**
 * What each fal endpoint will accept, read from fal's own OpenAPI schemas.
 *
 * GENERATED by scripts/fetch-fal-params.py. Do not edit by hand — re-run the
 * script after adding a model in /admin/models.
 *
 * This exists because fal validates strictly and bills first: a field an
 * endpoint has never heard of comes back 422 on a request that has already been
 * paid for. The panel offers size, output format and quality; which of those an
 * endpoint takes, under which name, and with which values, differs per endpoint
 * in ways that are not guessable — Kontext takes `aspect_ratio` where Ideogram
 * takes `image_size`, FLUX accepts only jpeg and png where Nano Banana also
 * takes webp, and a vectoriser takes none of it.
 *
 * A hand-written version of this table had four errors. This one is read from
 * the source.
 *
 * An endpoint absent from this table accepts none of these parameters, which is
 * the safe reading: applyParams sends nothing it cannot find here.
 */

/** Field name to the values that field allows. */
export type FalParamSupport = Readonly<Record<string, readonly string[]>>;

export const FAL_PARAM_SUPPORT: Readonly<Record<string, FalParamSupport>> =
  {
  "bytedance/seedance-2.0/fast/image-to-video": {
    "aspect_ratio": [
      "16:9",
      "1:1",
      "21:9",
      "3:4",
      "4:3",
      "9:16",
      "auto"
    ]
  },
  "bytedance/seedance-2.5/image-to-video": {
    "aspect_ratio": []
  },
  "fal-ai/birefnet/v2": {
    "output_format": [
      "gif",
      "png",
      "webp"
    ]
  },
  "fal-ai/flux-lora": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "num_inference_steps": [],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux-lora/image-to-image": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "num_inference_steps": [],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux-lora/inpainting": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "num_inference_steps": [],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux-pro/kontext": {
    "aspect_ratio": [
      "16:9",
      "1:1",
      "21:9",
      "2:3",
      "3:2",
      "3:4",
      "4:3",
      "9:16",
      "9:21"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux-pro/kontext/max": {
    "aspect_ratio": [
      "16:9",
      "1:1",
      "21:9",
      "2:3",
      "3:2",
      "3:4",
      "4:3",
      "9:16",
      "9:21"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux/dev": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "num_inference_steps": [],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux/dev/image-to-image": {
    "num_inference_steps": [],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/ideogram/v3": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ]
  },
  "fal-ai/krea-2/turbo": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/krea-2/turbo/image-to-image": {
    "image_size": [
      "auto",
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/nano-banana-pro": {
    "aspect_ratio": [
      "16:9",
      "1:1",
      "21:9",
      "2:3",
      "3:2",
      "3:4",
      "4:3",
      "4:5",
      "5:4",
      "9:16",
      "auto"
    ],
    "output_format": [
      "jpeg",
      "png",
      "webp"
    ]
  },
  "fal-ai/nano-banana/edit": {
    "aspect_ratio": [
      "16:9",
      "1:1",
      "21:9",
      "2:3",
      "3:2",
      "3:4",
      "4:3",
      "4:5",
      "5:4",
      "9:16",
      "auto"
    ],
    "output_format": [
      "jpeg",
      "png",
      "webp"
    ]
  },
  "fal-ai/recraft/v4.1/text-to-vector": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ]
  },
  "fal-ai/recraft/v4/pro/text-to-vector": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ]
  },
  "fal-ai/veo3.1/fast/image-to-video": {
    "aspect_ratio": [
      "16:9",
      "9:16",
      "auto"
    ]
  },
  "fal-ai/veo3.1/image-to-video": {
    "aspect_ratio": [
      "16:9",
      "9:16",
      "auto"
    ]
  },
  "fal-ai/veo3.1/lite/image-to-video": {
    "aspect_ratio": [
      "16:9",
      "9:16",
      "auto"
    ]
  },
  "ideogram/v4/image-to-image": {
    "image_size": [
      "auto",
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "ideogram/v4/instant": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "openai/gpt-image-2": {
    "image_size": [
      "auto",
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png",
      "webp"
    ],
    "quality": [
      "auto",
      "high",
      "low",
      "medium"
    ]
  },
  "openai/gpt-image-2/edit": {
    "image_size": [
      "auto",
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png",
      "webp"
    ],
    "quality": [
      "auto",
      "high",
      "low",
      "medium"
    ]
  }
} as const;

/**
 * How an endpoint wants a clip's length.
 *
 * Its own table rather than a field in the one above, because that one holds
 * string allowlists and a duration is not always a string: Veo declares
 * "4s"/"6s"/"8s", Kling declares "5"/"10", and Wan, MiniMax, PixVerse and
 * Happy Horse declare a plain integer. Sending the wrong *type* is refused the
 * same way sending the wrong value is — 422, after the generation is billed.
 *
 * `values` empty means the endpoint constrains the length by range instead;
 * `min`/`max` carry it. An endpoint absent here takes no duration at all.
 */
export interface FalDuration {
  /** "integer" means send a number, not the string of one. */
  kind: "integer" | "string";
  max?: number;
  min?: number;
  /** The allowed lengths, written as text whatever the wire type. */
  values: readonly string[];
}

export const FAL_DURATION: Readonly<Record<string, FalDuration>> =
  {
  "alibaba/happy-horse/image-to-video": {
    "kind": "integer",
    "values": [
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ]
  },
  "bytedance/seedance-2.0/fast/image-to-video": {
    "kind": "string",
    "values": [
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "auto"
    ]
  },
  "bytedance/seedance-2.5/image-to-video": {
    "kind": "string",
    "values": [
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "auto"
    ]
  },
  "fal-ai/kling-video/v2.5-turbo/pro/image-to-video": {
    "kind": "string",
    "values": [
      "10",
      "5"
    ]
  },
  "fal-ai/kling-video/v3/pro/image-to-video": {
    "kind": "string",
    "values": [
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ]
  },
  "fal-ai/kling-video/v3/standard/image-to-video": {
    "kind": "string",
    "values": [
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ]
  },
  "fal-ai/pixverse/v6/image-to-video": {
    "kind": "integer",
    "max": 15,
    "min": 1,
    "values": []
  },
  "fal-ai/veo3.1/fast/image-to-video": {
    "kind": "string",
    "values": [
      "4s",
      "6s",
      "8s"
    ]
  },
  "fal-ai/veo3.1/image-to-video": {
    "kind": "string",
    "values": [
      "4s",
      "6s",
      "8s"
    ]
  },
  "fal-ai/veo3.1/lite/image-to-video": {
    "kind": "string",
    "values": [
      "4s",
      "6s",
      "8s"
    ]
  },
  "fal-ai/wan/v2.7/image-to-video": {
    "kind": "integer",
    "values": [
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ]
  },
  "minimax/h3/image-to-video": {
    "kind": "integer",
    "max": 15,
    "min": 5,
    "values": []
  }
} as const;
